name: CI ThingsBoard

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install Maven
        run: sudo apt-get install maven

      - name: Build and run unit tests
        run: mvn clean install -DskipITs -Dlicense.skip=true -pl common/util,common/data -am

      - name: Start ThingsBoard using Docker
        run: |
          docker pull thingsboard/tb-postgres:latest
          docker run -d --name tb-postgres -p 5432:5432 thingsboard/tb-postgres:latest
          docker pull thingsboard/tb:latest
          docker run -d --name thingsboard -p 8080:8080 --link tb-postgres:tb-postgres thingsboard/tb:latest

      - name: Check ThingsBoard is running
        run: |
          sleep 60
          curl -f http://localhost:8080 || exit 1

      - name: Clean up ThingsBoard container
        run: |
          docker stop thingsboard
          docker rm thingsboard
          docker stop tb-postgres
          docker rm tb-postgres